services:
  ccf-sandbox:
    image: azurekms.azurecr.io/ccf_sandbox/${CCF_PLATFORM:-virtual}:ccf-5.0.11
    extends:
      file: ./ccf-sandbox/docker-compose.yml
      service: ccf-sandbox

  ccf-sandbox-joiner:
    image: azurekms.azurecr.io/ccf_sandbox/${CCF_PLATFORM:-virtual}:ccf-5.0.11
    extends:
      file: ./ccf-sandbox/docker-compose.yml
      service: ccf-sandbox-joiner

  jwt-issuer:
    image: azurekms.azurecr.io/jwt_issuer:latest
    build:
      context: ../test/utils/jwt
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - KMS_WORKSPACE=/workspace
      - JWT_ISSUER_PORT=${JWT_ISSUER_PORT:-}
    healthcheck:
      test: "curl -k --fail -X POST $(cat /workspace/jwt_issuer_address)/token"
      interval: 1s
      retries: 120
    volumes:
      - ${JWT_ISSUER_WORKSPACE:-../jwt_issuers_workspace/default}:/workspace
